{{- if .Values.allowGateway.enabled }}
# Gateway → 모든 goti 서비스 허용
# 외부 트래픽은 Istio Gateway를 통해서만 진입
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-istio-gateway
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - {{ .Values.allowGateway.gatewaySA | quote }}
{{- end }}
