{{- range .Values.serviceEntries }}
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: {{ .name }}
spec:
  hosts:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
  {{- with .addresses }}
  addresses:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  location: {{ .location | default "MESH_EXTERNAL" }}
  ports:
    {{- toYaml .ports | nindent 4 }}
  resolution: {{ .resolution | default "DNS" }}
  {{- with .endpoints }}
  endpoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
