apiVersion: v2
name: istio-gateway
description: Istio Ingress Gateway Helm wrapper
version: 0.1.0
dependencies:
  - name: gateway
    version: "1.29.0"
    repository: "https://istio-release.storage.googleapis.com/charts"
