apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflare-exporter
  namespace: monitoring
  labels:
    app: cloudflare-exporter
    release: kube-prometheus-stack-dev
spec:
  selector:
    matchLabels:
      app: cloudflare-exporter
  endpoints:
    - port: metrics
      interval: 60s
      path: /metrics
