replicaCount: 2
image:
  repository: "asia-northeast3-docker.pkg.dev/goti-gcp/goti-prod-registry/goti-user"
  tag: "prod-46-e652be4"
  pullPolicy: IfNotPresent
# GCP: Workload Identity handles Artifact Registry auth
imagePullSecrets: []
externalSecret:
  enabled: true
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  remoteRef:
    nameRegexp: "^goti-prod-server-"
    nameRewriteSource: "^goti-prod-server-(.*)$"
    overrideNameRegexp: "^goti-prod-user-"
    overrideNameRewriteSource: "^goti-prod-user-(.*)$"
istioPolicy:
  sidecar:
    enabled: true
    egress:
      - hosts:
          - "istio-system/*"
          - "./*"
          - "monitoring/*"
          - "~/*.googleapis.com"
          - "~/*.naver.com"
          - "~/*.kakao.com"
          - "~/*.nurigo.com"
