replicaCount: 4
image:
  repository: "707925622666.dkr.ecr.ap-northeast-2.amazonaws.com/goti-user-go"
  pullPolicy: IfNotPresent
externalSecret:
  enabled: true
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  remoteRef:
    path: /prod/user-go
istioPolicy:
  sidecar:
    enabled: true
    egress:
      - hosts:
          - "istio-system/*"
          - "./*"
          - "monitoring/*"
          - "~/*.amazonaws.com"
# Cutover: Go 활성화
gateway:
  enabled: true
