apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: github-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: /prod/argocd/GITHUB_PAT
