# GCP Secret Manager에서 ArgoCD GitOps repo 접근 토큰 가져오기
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitops-repo
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: gitops-repo
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: "https://github.com/Team-Ikujo/Goti-k8s"
        username: git
        password: "{{ .pat }}"
  data:
    - secretKey: pat
      remoteRef:
        key: goti-prod-argocd-github-pat
