# GCP Secret Manager에서 Grafana admin 자격증명 가져오기
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: goti-prod-monitoring-GF_SECURITY_ADMIN_USER
    - secretKey: admin-password
      remoteRef:
        key: goti-prod-monitoring-GF_SECURITY_ADMIN_PASSWORD
