nameOverride: goti-payment
replicaCount: 2
image:
  repository: "asia-northeast3-docker.pkg.dev/goti-gcp/goti-prod-registry/goti-payment"
  tag: "prod-43-6f4c644"
  pullPolicy: IfNotPresent
imagePullSecrets: []
podAnnotations:
  instrumentation.opentelemetry.io/inject-java: "goti/goti-java"
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
probes:
  liveness:
    httpGet:
      path: /actuator/health/liveness
      port: http
    initialDelaySeconds: 60
    periodSeconds: 10
  readiness:
    httpGet:
      path: /actuator/health/readiness
      port: http
    initialDelaySeconds: 30
    periodSeconds: 5
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"
  - name: JAVA_TOOL_OPTIONS
    value: "-XX:MaxRAMPercentage=60.0"
  - name: REDIS_PORT
    value: "6379"
  - name: SPRING_DATA_REDIS_SSL_ENABLED
    value: "true"
  - name: SPRING_DATA_REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: goti-payment-prod-secrets
        key: REDIS_AUTH_TOKEN
envFrom:
  - secretRef:
      name: goti-payment-prod-secrets
externalSecret:
  enabled: true
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  remoteRef:
    nameRegexp: "^goti-prod-server-"
    nameRewriteSource: "^goti-prod-server-(.*)$"
    overrideNameRegexp: "^goti-prod-payment-"
    overrideNameRewriteSource: "^goti-prod-payment-(.*)$"
istioPolicy:
  authorizationPolicy:
    enabled: true
    allowFrom: []
  requestAuthentication:
    enabled: true
    jwksUri: "http://goti-user-prod.goti.svc.cluster.local:8080/.well-known/jwks.json"
  jwtAuthorizationPolicy:
    enabled: true
    excludePaths:
      - "/actuator"
      - "/actuator/*"
  destinationRule:
    enabled: true
  sidecar:
    enabled: true
    egress:
      - hosts:
          - "istio-system/*"
          - "./*"
          - "monitoring/*"
          - "kafka/*"
