config:
  registries:
    - name: ECR
      api_url: https://707925622666.dkr.ecr.ap-northeast-2.amazonaws.com
      prefix: 707925622666.dkr.ecr.ap-northeast-2.amazonaws.com
      credentials: pullsecret:argocd/ecr-creds
