replicaCount: 2
externalSecret:
  enabled: true
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  remoteRef:
    path: /prod/server
    overridePath: /prod/resale
istioPolicy:
  sidecar:
    enabled: true
    egress:
      - hosts:
          - "istio-system/*"
          - "./*"
          - "monitoring/*"
          - "kafka/*"
          - "~/*.amazonaws.com"
