# Pyroscope dev-kind values
pyroscope:
  structuredConfig:
    storage:
      backend: filesystem
      filesystem:
        dir: /data
  extraArgs:
    pyroscopedb.retention-period: "72h"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    size: 5Gi
