# Tempo dev-kind values
serviceAccount:
  automountServiceAccountToken: false

tempo:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"
    zipkin:
      endpoint: "0.0.0.0:9411"
  metricsGenerator:
    enabled: true
    config:
      storage:
        remote_write:
          - url: "http://kube-prometheus-stack-prometheus.monitoring.svc:9090/api/v1/write"
            send_exemplars: true
    processors:
      - service-graphs
      - span-metrics
  compactor:
    compaction:
      block_retention: 72h
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

persistence:
  enabled: true
  size: 5Gi

tempoQuery:
  enabled: false
