nameOverride: goti-stadium
image:
  repository: "harbor.go-ti.shop/prod/goti-stadium"
  tag: "prod-24-71dcf1b"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: harbor-creds
podAnnotations:
  instrumentation.opentelemetry.io/inject-java: "goti/goti-java"
resources:
  requests:
    cpu: 250m
    memory: 384Mi
  limits:
    cpu: 1000m
    memory: 768Mi
gateway:
  enabled: true
  hosts:
    - "go-ti.shop"
    - "api.go-ti.shop"
  gatewayRef: "istio-system/goti-shared-gateway"
  httpRoutes:
    - match:
        - uri:
            exact: "/api/v1/stadiums"
        - uri:
            prefix: "/api/v1/baseball-teams"
      route:
        - destination:
            host: goti-stadium-prod
            port:
              number: 8080
    - match:
        - uri:
            prefix: "/api/docs/stadium/swagger-ui/"
      rewrite:
        uri: "/swagger-ui/"
      route:
        - destination:
            host: goti-stadium-prod
            port:
              number: 8080
    - match:
        - uri:
            prefix: "/api/docs/stadium/v3/"
      rewrite:
        uri: "/v3/"
      route:
        - destination:
            host: goti-stadium-prod
            port:
              number: 8080
probes:
  liveness:
    httpGet:
      path: /actuator/health/liveness
      port: http
    initialDelaySeconds: 60
    periodSeconds: 10
  readiness:
    httpGet:
      path: /actuator/health/readiness
      port: http
    initialDelaySeconds: 30
    periodSeconds: 5
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"
  - name: JAVA_TOOL_OPTIONS
    value: "-XX:MaxRAMPercentage=60.0"
  - name: REDIS_PORT
    value: "6379"
  - name: SPRING_DATA_REDIS_SSL_ENABLED
    value: "true"
  - name: SPRING_DATA_REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: goti-stadium-prod-secrets
        key: REDIS_AUTH_TOKEN
  - name: SPRINGDOC_SWAGGER_UI_CONFIG_URL
    value: "/api/docs/stadium/v3/api-docs/swagger-config"
  - name: SPRINGDOC_SWAGGER_UI_URL
    value: "/api/docs/stadium/v3/api-docs"
envFrom:
  - secretRef:
      name: goti-stadium-prod-secrets
externalSecret:
  enabled: true
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  remoteRef:
    path: /prod/server
    overridePath: /prod/stadium
