apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-google-oauth
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.googleOAuth.secretStore }}
    kind: ClusterSecretStore
  target:
    name: argocd-google-oauth
    creationPolicy: Owner
  data:
    - secretKey: clientID
      remoteRef:
        key: {{ .Values.googleOAuth.clientIdKey }}
    - secretKey: clientSecret
      remoteRef:
        key: {{ .Values.googleOAuth.clientSecretKey }}
    

       