apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: goti
  namespace: argocd
spec:
  description: "Goti 애플리케이션 프로젝트"
  sourceRepos:
    - "https://github.com/Team-Ikujo/Goti-k8s.git"
  destinations:
    - namespace: goti
      server: "https://kubernetes.default.svc"
    - namespace: goti-*
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: Endpoints
    - group: "apps"
      kind: Deployment
    - group: "apps"
      kind: StatefulSet
    - group: "apps"
      kind: ReplicaSet
    - group: "autoscaling"
      kind: HorizontalPodAutoscaler
    - group: "policy"
      kind: PodDisruptionBudget
    - group: "networking.k8s.io"
      kind: Ingress
    - group: "networking.k8s.io"
      kind: NetworkPolicy
    - group: "networking.istio.io"
      kind: Gateway
    - group: "networking.istio.io"
      kind: VirtualService
    - group: "networking.istio.io"
      kind: DestinationRule
    - group: "networking.istio.io"
      kind: ServiceEntry
    - group: "security.istio.io"
      kind: PeerAuthentication
    - group: "security.istio.io"
      kind: AuthorizationPolicy
    - group: "security.istio.io"
      kind: RequestAuthentication
    - group: "external-secrets.io"
      kind: ExternalSecret
