apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: infra
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: "1.18.3"
      helm:
        valueFiles:
          - $values/infrastructure/prod/harbor/values.yaml
    - repoURL: https://github.com/Team-Ikujo/Goti-k8s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
