nameOverride: goti-payment

image:
  repository: "707925622666.dkr.ecr.ap-northeast-2.amazonaws.com/goti-payment"
  tag: "dev-35-de629ba"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-creds

podAnnotations:
  instrumentation.opentelemetry.io/inject-java: "goti/goti-java"

resources:
  requests:
    cpu: 250m
    memory: 384Mi
  limits:
    cpu: 1000m
    memory: 768Mi

gateway:
  enabled: true
  hosts:
    - "go-ti.shop"
  gatewayRef: "istio-system/goti-shared-gateway"
  httpRoutes:
    - match:
        - uri:
            prefix: "/api/v1/payments"
      route:
        - destination:
            host: goti-payment-prod
            port:
              number: 8080
    - match:
        - uri:
            prefix: "/api/docs/payment/swagger-ui/"
      rewrite:
        uri: "/swagger-ui/"
      route:
        - destination:
            host: goti-payment-prod
            port:
              number: 8080
    - match:
        - uri:
            prefix: "/api/docs/payment/v3/"
      rewrite:
        uri: "/v3/"
      route:
        - destination:
            host: goti-payment-prod
            port:
              number: 8080

probes:
  liveness:
    httpGet:
      path: /actuator/health/liveness
      port: http
    initialDelaySeconds: 60
    periodSeconds: 10
  readiness:
    httpGet:
      path: /actuator/health/readiness
      port: http
    initialDelaySeconds: 30
    periodSeconds: 5

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"
  - name: JAVA_TOOL_OPTIONS
    value: "-XX:MaxRAMPercentage=60.0"
  - name: SPRINGDOC_SWAGGER_UI_CONFIG_URL
    value: "/api/docs/payment/v3/api-docs/swagger-config"
  - name: SPRINGDOC_SWAGGER_UI_URL
    value: "/api/docs/payment/v3/api-docs"

envFrom:
  - secretRef:
      name: goti-payment-prod-secrets

externalSecret:
  enabled: true
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  remoteRef:
    path: /prod/payment
