replicaCount: 2
image:
  repository: "707925622666.dkr.ecr.ap-northeast-2.amazonaws.com/prod/goti-payment"
  tag: "prod-43-6f4c644"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ecr-creds
externalSecret:
  enabled: true
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  remoteRef:
    path: /prod/server
    overridePath: /prod/payment
istioPolicy:
  sidecar:
    enabled: true
    egress:
      - hosts:
          - "istio-system/*"
          - "./*"
          - "monitoring/*"
          - "kafka/*"
          - "~/*.amazonaws.com"
