apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: goti-infra-gcp
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - service: load-observer
            namespace: goti
            valuesFile: environments/prod-gcp/goti-load-observer/values.yaml
  template:
    metadata:
      name: "goti-{{service}}-prod-gcp"
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=true
    spec:
      project: goti
      source:
        repoURL: "https://github.com/Team-Ikujo/Goti-k8s.git"
        targetRevision: main
        path: "charts/goti-server"
        helm:
          valueFiles:
            - "../../{{valuesFile}}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - PruneLast=true
          - PrunePropagationPolicy=foreground
