architecture: standalone

auth:
  enabled: false

master:
  podAnnotations:
    sidecar.istio.io/inject: "false"
    kyverno.io/exclude-image-tag-policy: "true"
    kyverno.io/exclude-label-policy: "true"
    kyverno.io/exclude-resource-limits: "true"
  persistence:
    enabled: true
    storageClass: gp3
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
