apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecr-credential-renewer
  namespace: argocd
spec:
  project: goti
  source:
    repoURL: "https://github.com/Team-Ikujo/Goti-k8s.git"
    targetRevision: main
    path: manifests
    directory:
      include: "ecr-credential-renewer.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: goti
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
