apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swagger-ui
  namespace: argocd
spec:
  project: goti
  source:
    repoURL: "https://github.com/Team-Ikujo/Goti-k8s.git"
    targetRevision: main
    path: "charts/swagger-ui"
    helm:
      valueFiles:
        - "../../environments/dev/swagger-ui/values.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: goti
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
