# Storage 클래스 관리 ArgoCD Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Team-Ikujo/Goti-k8s.git
    targetRevision: main
    path: infrastructure/prod/storage
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
