replicaCount: 2
image:
  repository: "harbor.go-ti.shop/prod/goti-ticketing"
  tag: "prod-53-a630ef6"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: harbor-creds
externalSecret:
  enabled: true
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  remoteRef:
    path: /prod/server
    overridePath: /prod/ticketing
istioPolicy:
  sidecar:
    enabled: true
    egress:
      - hosts:
          - "istio-system/*"
          - "./*"
          - "monitoring/*"
          - "kafka/*"
          - "~/*.amazonaws.com"
