name: Get Role Trust

on:
  workflow_dispatch:

jobs:
  get:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-2

      - name: Get Specific Role
        run: |
          aws iam get-role --role-name goti-dev-github-actions-ro --output json 2>&1
