name: K8s Secrets Extract

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Show AWS Role ARN
        run: |
          echo "=== AWS ROLE ==="
          echo "AWS_ROLE_ARN=$AWS_ROLE_ARN"
        env:
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
