{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "goti-common.fullname" . }}-secrets
  labels:
    {{- include "goti-common.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ include "goti-common.fullname" . }}-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        path: {{ .Values.externalSecret.remoteRef.path }}
        name:
          regexp: ".*"
      rewrite:
        - regexp:
            source: "^{{ .Values.externalSecret.remoteRef.path }}/(.*)$"
            target: "$1"
    {{- if .Values.externalSecret.remoteRef.overridePath }}
    - find:
        path: {{ .Values.externalSecret.remoteRef.overridePath }}
        name:
          regexp: ".*"
      rewrite:
        - regexp:
            source: "^{{ .Values.externalSecret.remoteRef.overridePath }}/(.*)$"
            target: "$1"
    {{- end }}
{{- end }}
