image:
  repository: "707925622666.dkr.ecr.ap-northeast-2.amazonaws.com/goti-server"
  tag: "dev-latest"
  pullPolicy: Always

imagePullSecrets:
  - name: ecr-creds

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

gateway:
  enabled: true
  hosts:
    - "goti.local"

probes:
  liveness:
    httpGet:
      path: /actuator/health/liveness
      port: http
    initialDelaySeconds: 60
    periodSeconds: 10
  readiness:
    httpGet:
      path: /actuator/health/readiness
      port: http
    initialDelaySeconds: 30
    periodSeconds: 5

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "dev"
  - name: JAVA_TOOL_OPTIONS
    value: "-Xms256m -Xmx384m"

envFrom:
  - secretRef:
      name: goti-server-secrets    # ExternalSecret이 SSM에서 자동 생성

externalSecret:
  enabled: true
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  remoteRef:
    path: /dev/server
